language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jamesfrj/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesfrj/docker-react-example npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  name: "docker-react-example"
  env: "Dockerreactexample-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-624375836866"
  bucket_path: "docker-react-example"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY